"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['icon.icns', 'Resources']
OPTIONS = {
    'iconfile':'icon.icns',
    'plist': {
        'CFBundleName'   : 'Markdown & Docx', # 应用名
        'CFBundleDisplayName': 'Markdown & Docx', # 应用显示名
        'CFBundleVersion': '2.0.0',
        'CFBundleIdentifier' : 'Markdown_exchange_Docx', # 应用包名、唯一标识
        'includes': ['os', 'tkinter', 'pypandoc']
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
